// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: svg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_svg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_svg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_svg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_svg_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_svg_2eproto;
namespace transport_catalog_serialize {
class Color;
struct ColorDefaultTypeInternal;
extern ColorDefaultTypeInternal _Color_default_instance_;
class Point;
struct PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
class RGB;
struct RGBDefaultTypeInternal;
extern RGBDefaultTypeInternal _RGB_default_instance_;
class RGBA;
struct RGBADefaultTypeInternal;
extern RGBADefaultTypeInternal _RGBA_default_instance_;
}  // namespace transport_catalog_serialize
PROTOBUF_NAMESPACE_OPEN
template<> ::transport_catalog_serialize::Color* Arena::CreateMaybeMessage<::transport_catalog_serialize::Color>(Arena*);
template<> ::transport_catalog_serialize::Point* Arena::CreateMaybeMessage<::transport_catalog_serialize::Point>(Arena*);
template<> ::transport_catalog_serialize::RGB* Arena::CreateMaybeMessage<::transport_catalog_serialize::RGB>(Arena*);
template<> ::transport_catalog_serialize::RGBA* Arena::CreateMaybeMessage<::transport_catalog_serialize::RGBA>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace transport_catalog_serialize {

// ===================================================================

class Point final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalog_serialize.Point) */ {
 public:
  inline Point() : Point(nullptr) {}
  ~Point() override;
  explicit PROTOBUF_CONSTEXPR Point(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Point(const Point& from);
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point& operator=(Point&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Point& default_instance() {
    return *internal_default_instance();
  }
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }
  inline void Swap(Point* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Point* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Point& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Point& from) {
    Point::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalog_serialize.Point";
  }
  protected:
  explicit Point(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // @@protoc_insertion_point(class_scope:transport_catalog_serialize.Point)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double x_;
    double y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_svg_2eproto;
};
// -------------------------------------------------------------------

class RGB final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalog_serialize.RGB) */ {
 public:
  inline RGB() : RGB(nullptr) {}
  ~RGB() override;
  explicit PROTOBUF_CONSTEXPR RGB(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RGB(const RGB& from);
  RGB(RGB&& from) noexcept
    : RGB() {
    *this = ::std::move(from);
  }

  inline RGB& operator=(const RGB& from) {
    CopyFrom(from);
    return *this;
  }
  inline RGB& operator=(RGB&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RGB& default_instance() {
    return *internal_default_instance();
  }
  static inline const RGB* internal_default_instance() {
    return reinterpret_cast<const RGB*>(
               &_RGB_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RGB& a, RGB& b) {
    a.Swap(&b);
  }
  inline void Swap(RGB* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RGB* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RGB* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RGB>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RGB& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RGB& from) {
    RGB::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RGB* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalog_serialize.RGB";
  }
  protected:
  explicit RGB(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRedFieldNumber = 1,
    kGreenFieldNumber = 2,
    kBlueFieldNumber = 3,
  };
  // uint32 red = 1;
  void clear_red();
  uint32_t red() const;
  void set_red(uint32_t value);
  private:
  uint32_t _internal_red() const;
  void _internal_set_red(uint32_t value);
  public:

  // uint32 green = 2;
  void clear_green();
  uint32_t green() const;
  void set_green(uint32_t value);
  private:
  uint32_t _internal_green() const;
  void _internal_set_green(uint32_t value);
  public:

  // uint32 blue = 3;
  void clear_blue();
  uint32_t blue() const;
  void set_blue(uint32_t value);
  private:
  uint32_t _internal_blue() const;
  void _internal_set_blue(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:transport_catalog_serialize.RGB)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t red_;
    uint32_t green_;
    uint32_t blue_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_svg_2eproto;
};
// -------------------------------------------------------------------

class RGBA final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalog_serialize.RGBA) */ {
 public:
  inline RGBA() : RGBA(nullptr) {}
  ~RGBA() override;
  explicit PROTOBUF_CONSTEXPR RGBA(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RGBA(const RGBA& from);
  RGBA(RGBA&& from) noexcept
    : RGBA() {
    *this = ::std::move(from);
  }

  inline RGBA& operator=(const RGBA& from) {
    CopyFrom(from);
    return *this;
  }
  inline RGBA& operator=(RGBA&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RGBA& default_instance() {
    return *internal_default_instance();
  }
  static inline const RGBA* internal_default_instance() {
    return reinterpret_cast<const RGBA*>(
               &_RGBA_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RGBA& a, RGBA& b) {
    a.Swap(&b);
  }
  inline void Swap(RGBA* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RGBA* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RGBA* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RGBA>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RGBA& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RGBA& from) {
    RGBA::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RGBA* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalog_serialize.RGBA";
  }
  protected:
  explicit RGBA(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRedFieldNumber = 1,
    kGreenFieldNumber = 2,
    kOpacityFieldNumber = 4,
    kBlueFieldNumber = 3,
  };
  // uint32 red = 1;
  void clear_red();
  uint32_t red() const;
  void set_red(uint32_t value);
  private:
  uint32_t _internal_red() const;
  void _internal_set_red(uint32_t value);
  public:

  // uint32 green = 2;
  void clear_green();
  uint32_t green() const;
  void set_green(uint32_t value);
  private:
  uint32_t _internal_green() const;
  void _internal_set_green(uint32_t value);
  public:

  // double opacity = 4;
  void clear_opacity();
  double opacity() const;
  void set_opacity(double value);
  private:
  double _internal_opacity() const;
  void _internal_set_opacity(double value);
  public:

  // uint32 blue = 3;
  void clear_blue();
  uint32_t blue() const;
  void set_blue(uint32_t value);
  private:
  uint32_t _internal_blue() const;
  void _internal_set_blue(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:transport_catalog_serialize.RGBA)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t red_;
    uint32_t green_;
    double opacity_;
    uint32_t blue_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_svg_2eproto;
};
// -------------------------------------------------------------------

class Color final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalog_serialize.Color) */ {
 public:
  inline Color() : Color(nullptr) {}
  ~Color() override;
  explicit PROTOBUF_CONSTEXPR Color(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Color(const Color& from);
  Color(Color&& from) noexcept
    : Color() {
    *this = ::std::move(from);
  }

  inline Color& operator=(const Color& from) {
    CopyFrom(from);
    return *this;
  }
  inline Color& operator=(Color&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Color& default_instance() {
    return *internal_default_instance();
  }
  enum ColorsCase {
    kNoColor = 1,
    kColorName = 2,
    kRgb = 3,
    kRgba = 4,
    COLORS_NOT_SET = 0,
  };

  static inline const Color* internal_default_instance() {
    return reinterpret_cast<const Color*>(
               &_Color_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Color& a, Color& b) {
    a.Swap(&b);
  }
  inline void Swap(Color* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Color* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Color* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Color>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Color& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Color& from) {
    Color::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Color* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalog_serialize.Color";
  }
  protected:
  explicit Color(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNoColorFieldNumber = 1,
    kColorNameFieldNumber = 2,
    kRgbFieldNumber = 3,
    kRgbaFieldNumber = 4,
  };
  // bool no_color = 1;
  bool has_no_color() const;
  private:
  bool _internal_has_no_color() const;
  public:
  void clear_no_color();
  bool no_color() const;
  void set_no_color(bool value);
  private:
  bool _internal_no_color() const;
  void _internal_set_no_color(bool value);
  public:

  // string color_name = 2;
  bool has_color_name() const;
  private:
  bool _internal_has_color_name() const;
  public:
  void clear_color_name();
  const std::string& color_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_color_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_color_name();
  PROTOBUF_NODISCARD std::string* release_color_name();
  void set_allocated_color_name(std::string* color_name);
  private:
  const std::string& _internal_color_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_color_name(const std::string& value);
  std::string* _internal_mutable_color_name();
  public:

  // .transport_catalog_serialize.RGB rgb = 3;
  bool has_rgb() const;
  private:
  bool _internal_has_rgb() const;
  public:
  void clear_rgb();
  const ::transport_catalog_serialize::RGB& rgb() const;
  PROTOBUF_NODISCARD ::transport_catalog_serialize::RGB* release_rgb();
  ::transport_catalog_serialize::RGB* mutable_rgb();
  void set_allocated_rgb(::transport_catalog_serialize::RGB* rgb);
  private:
  const ::transport_catalog_serialize::RGB& _internal_rgb() const;
  ::transport_catalog_serialize::RGB* _internal_mutable_rgb();
  public:
  void unsafe_arena_set_allocated_rgb(
      ::transport_catalog_serialize::RGB* rgb);
  ::transport_catalog_serialize::RGB* unsafe_arena_release_rgb();

  // .transport_catalog_serialize.RGBA rgba = 4;
  bool has_rgba() const;
  private:
  bool _internal_has_rgba() const;
  public:
  void clear_rgba();
  const ::transport_catalog_serialize::RGBA& rgba() const;
  PROTOBUF_NODISCARD ::transport_catalog_serialize::RGBA* release_rgba();
  ::transport_catalog_serialize::RGBA* mutable_rgba();
  void set_allocated_rgba(::transport_catalog_serialize::RGBA* rgba);
  private:
  const ::transport_catalog_serialize::RGBA& _internal_rgba() const;
  ::transport_catalog_serialize::RGBA* _internal_mutable_rgba();
  public:
  void unsafe_arena_set_allocated_rgba(
      ::transport_catalog_serialize::RGBA* rgba);
  ::transport_catalog_serialize::RGBA* unsafe_arena_release_rgba();

  void clear_colors();
  ColorsCase colors_case() const;
  // @@protoc_insertion_point(class_scope:transport_catalog_serialize.Color)
 private:
  class _Internal;
  void set_has_no_color();
  void set_has_color_name();
  void set_has_rgb();
  void set_has_rgba();

  inline bool has_colors() const;
  inline void clear_has_colors();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ColorsUnion {
      constexpr ColorsUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      bool no_color_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr color_name_;
      ::transport_catalog_serialize::RGB* rgb_;
      ::transport_catalog_serialize::RGBA* rgba_;
    } colors_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_svg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Point

// double x = 1;
inline void Point::clear_x() {
  _impl_.x_ = 0;
}
inline double Point::_internal_x() const {
  return _impl_.x_;
}
inline double Point::x() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Point.x)
  return _internal_x();
}
inline void Point::_internal_set_x(double value) {
  
  _impl_.x_ = value;
}
inline void Point::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Point.x)
}

// double y = 2;
inline void Point::clear_y() {
  _impl_.y_ = 0;
}
inline double Point::_internal_y() const {
  return _impl_.y_;
}
inline double Point::y() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Point.y)
  return _internal_y();
}
inline void Point::_internal_set_y(double value) {
  
  _impl_.y_ = value;
}
inline void Point::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Point.y)
}

// -------------------------------------------------------------------

// RGB

// uint32 red = 1;
inline void RGB::clear_red() {
  _impl_.red_ = 0u;
}
inline uint32_t RGB::_internal_red() const {
  return _impl_.red_;
}
inline uint32_t RGB::red() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.RGB.red)
  return _internal_red();
}
inline void RGB::_internal_set_red(uint32_t value) {
  
  _impl_.red_ = value;
}
inline void RGB::set_red(uint32_t value) {
  _internal_set_red(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.RGB.red)
}

// uint32 green = 2;
inline void RGB::clear_green() {
  _impl_.green_ = 0u;
}
inline uint32_t RGB::_internal_green() const {
  return _impl_.green_;
}
inline uint32_t RGB::green() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.RGB.green)
  return _internal_green();
}
inline void RGB::_internal_set_green(uint32_t value) {
  
  _impl_.green_ = value;
}
inline void RGB::set_green(uint32_t value) {
  _internal_set_green(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.RGB.green)
}

// uint32 blue = 3;
inline void RGB::clear_blue() {
  _impl_.blue_ = 0u;
}
inline uint32_t RGB::_internal_blue() const {
  return _impl_.blue_;
}
inline uint32_t RGB::blue() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.RGB.blue)
  return _internal_blue();
}
inline void RGB::_internal_set_blue(uint32_t value) {
  
  _impl_.blue_ = value;
}
inline void RGB::set_blue(uint32_t value) {
  _internal_set_blue(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.RGB.blue)
}

// -------------------------------------------------------------------

// RGBA

// uint32 red = 1;
inline void RGBA::clear_red() {
  _impl_.red_ = 0u;
}
inline uint32_t RGBA::_internal_red() const {
  return _impl_.red_;
}
inline uint32_t RGBA::red() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.RGBA.red)
  return _internal_red();
}
inline void RGBA::_internal_set_red(uint32_t value) {
  
  _impl_.red_ = value;
}
inline void RGBA::set_red(uint32_t value) {
  _internal_set_red(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.RGBA.red)
}

// uint32 green = 2;
inline void RGBA::clear_green() {
  _impl_.green_ = 0u;
}
inline uint32_t RGBA::_internal_green() const {
  return _impl_.green_;
}
inline uint32_t RGBA::green() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.RGBA.green)
  return _internal_green();
}
inline void RGBA::_internal_set_green(uint32_t value) {
  
  _impl_.green_ = value;
}
inline void RGBA::set_green(uint32_t value) {
  _internal_set_green(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.RGBA.green)
}

// uint32 blue = 3;
inline void RGBA::clear_blue() {
  _impl_.blue_ = 0u;
}
inline uint32_t RGBA::_internal_blue() const {
  return _impl_.blue_;
}
inline uint32_t RGBA::blue() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.RGBA.blue)
  return _internal_blue();
}
inline void RGBA::_internal_set_blue(uint32_t value) {
  
  _impl_.blue_ = value;
}
inline void RGBA::set_blue(uint32_t value) {
  _internal_set_blue(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.RGBA.blue)
}

// double opacity = 4;
inline void RGBA::clear_opacity() {
  _impl_.opacity_ = 0;
}
inline double RGBA::_internal_opacity() const {
  return _impl_.opacity_;
}
inline double RGBA::opacity() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.RGBA.opacity)
  return _internal_opacity();
}
inline void RGBA::_internal_set_opacity(double value) {
  
  _impl_.opacity_ = value;
}
inline void RGBA::set_opacity(double value) {
  _internal_set_opacity(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.RGBA.opacity)
}

// -------------------------------------------------------------------

// Color

// bool no_color = 1;
inline bool Color::_internal_has_no_color() const {
  return colors_case() == kNoColor;
}
inline bool Color::has_no_color() const {
  return _internal_has_no_color();
}
inline void Color::set_has_no_color() {
  _impl_._oneof_case_[0] = kNoColor;
}
inline void Color::clear_no_color() {
  if (_internal_has_no_color()) {
    _impl_.colors_.no_color_ = false;
    clear_has_colors();
  }
}
inline bool Color::_internal_no_color() const {
  if (_internal_has_no_color()) {
    return _impl_.colors_.no_color_;
  }
  return false;
}
inline void Color::_internal_set_no_color(bool value) {
  if (!_internal_has_no_color()) {
    clear_colors();
    set_has_no_color();
  }
  _impl_.colors_.no_color_ = value;
}
inline bool Color::no_color() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Color.no_color)
  return _internal_no_color();
}
inline void Color::set_no_color(bool value) {
  _internal_set_no_color(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Color.no_color)
}

// string color_name = 2;
inline bool Color::_internal_has_color_name() const {
  return colors_case() == kColorName;
}
inline bool Color::has_color_name() const {
  return _internal_has_color_name();
}
inline void Color::set_has_color_name() {
  _impl_._oneof_case_[0] = kColorName;
}
inline void Color::clear_color_name() {
  if (_internal_has_color_name()) {
    _impl_.colors_.color_name_.Destroy();
    clear_has_colors();
  }
}
inline const std::string& Color::color_name() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Color.color_name)
  return _internal_color_name();
}
template <typename ArgT0, typename... ArgT>
inline void Color::set_color_name(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_color_name()) {
    clear_colors();
    set_has_color_name();
    _impl_.colors_.color_name_.InitDefault();
  }
  _impl_.colors_.color_name_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Color.color_name)
}
inline std::string* Color::mutable_color_name() {
  std::string* _s = _internal_mutable_color_name();
  // @@protoc_insertion_point(field_mutable:transport_catalog_serialize.Color.color_name)
  return _s;
}
inline const std::string& Color::_internal_color_name() const {
  if (_internal_has_color_name()) {
    return _impl_.colors_.color_name_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void Color::_internal_set_color_name(const std::string& value) {
  if (!_internal_has_color_name()) {
    clear_colors();
    set_has_color_name();
    _impl_.colors_.color_name_.InitDefault();
  }
  _impl_.colors_.color_name_.Set(value, GetArenaForAllocation());
}
inline std::string* Color::_internal_mutable_color_name() {
  if (!_internal_has_color_name()) {
    clear_colors();
    set_has_color_name();
    _impl_.colors_.color_name_.InitDefault();
  }
  return _impl_.colors_.color_name_.Mutable(      GetArenaForAllocation());
}
inline std::string* Color::release_color_name() {
  // @@protoc_insertion_point(field_release:transport_catalog_serialize.Color.color_name)
  if (_internal_has_color_name()) {
    clear_has_colors();
    return _impl_.colors_.color_name_.Release();
  } else {
    return nullptr;
  }
}
inline void Color::set_allocated_color_name(std::string* color_name) {
  if (has_colors()) {
    clear_colors();
  }
  if (color_name != nullptr) {
    set_has_color_name();
    _impl_.colors_.color_name_.InitAllocated(color_name, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:transport_catalog_serialize.Color.color_name)
}

// .transport_catalog_serialize.RGB rgb = 3;
inline bool Color::_internal_has_rgb() const {
  return colors_case() == kRgb;
}
inline bool Color::has_rgb() const {
  return _internal_has_rgb();
}
inline void Color::set_has_rgb() {
  _impl_._oneof_case_[0] = kRgb;
}
inline void Color::clear_rgb() {
  if (_internal_has_rgb()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.colors_.rgb_;
    }
    clear_has_colors();
  }
}
inline ::transport_catalog_serialize::RGB* Color::release_rgb() {
  // @@protoc_insertion_point(field_release:transport_catalog_serialize.Color.rgb)
  if (_internal_has_rgb()) {
    clear_has_colors();
    ::transport_catalog_serialize::RGB* temp = _impl_.colors_.rgb_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.colors_.rgb_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::transport_catalog_serialize::RGB& Color::_internal_rgb() const {
  return _internal_has_rgb()
      ? *_impl_.colors_.rgb_
      : reinterpret_cast< ::transport_catalog_serialize::RGB&>(::transport_catalog_serialize::_RGB_default_instance_);
}
inline const ::transport_catalog_serialize::RGB& Color::rgb() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Color.rgb)
  return _internal_rgb();
}
inline ::transport_catalog_serialize::RGB* Color::unsafe_arena_release_rgb() {
  // @@protoc_insertion_point(field_unsafe_arena_release:transport_catalog_serialize.Color.rgb)
  if (_internal_has_rgb()) {
    clear_has_colors();
    ::transport_catalog_serialize::RGB* temp = _impl_.colors_.rgb_;
    _impl_.colors_.rgb_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Color::unsafe_arena_set_allocated_rgb(::transport_catalog_serialize::RGB* rgb) {
  clear_colors();
  if (rgb) {
    set_has_rgb();
    _impl_.colors_.rgb_ = rgb;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalog_serialize.Color.rgb)
}
inline ::transport_catalog_serialize::RGB* Color::_internal_mutable_rgb() {
  if (!_internal_has_rgb()) {
    clear_colors();
    set_has_rgb();
    _impl_.colors_.rgb_ = CreateMaybeMessage< ::transport_catalog_serialize::RGB >(GetArenaForAllocation());
  }
  return _impl_.colors_.rgb_;
}
inline ::transport_catalog_serialize::RGB* Color::mutable_rgb() {
  ::transport_catalog_serialize::RGB* _msg = _internal_mutable_rgb();
  // @@protoc_insertion_point(field_mutable:transport_catalog_serialize.Color.rgb)
  return _msg;
}

// .transport_catalog_serialize.RGBA rgba = 4;
inline bool Color::_internal_has_rgba() const {
  return colors_case() == kRgba;
}
inline bool Color::has_rgba() const {
  return _internal_has_rgba();
}
inline void Color::set_has_rgba() {
  _impl_._oneof_case_[0] = kRgba;
}
inline void Color::clear_rgba() {
  if (_internal_has_rgba()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.colors_.rgba_;
    }
    clear_has_colors();
  }
}
inline ::transport_catalog_serialize::RGBA* Color::release_rgba() {
  // @@protoc_insertion_point(field_release:transport_catalog_serialize.Color.rgba)
  if (_internal_has_rgba()) {
    clear_has_colors();
    ::transport_catalog_serialize::RGBA* temp = _impl_.colors_.rgba_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.colors_.rgba_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::transport_catalog_serialize::RGBA& Color::_internal_rgba() const {
  return _internal_has_rgba()
      ? *_impl_.colors_.rgba_
      : reinterpret_cast< ::transport_catalog_serialize::RGBA&>(::transport_catalog_serialize::_RGBA_default_instance_);
}
inline const ::transport_catalog_serialize::RGBA& Color::rgba() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Color.rgba)
  return _internal_rgba();
}
inline ::transport_catalog_serialize::RGBA* Color::unsafe_arena_release_rgba() {
  // @@protoc_insertion_point(field_unsafe_arena_release:transport_catalog_serialize.Color.rgba)
  if (_internal_has_rgba()) {
    clear_has_colors();
    ::transport_catalog_serialize::RGBA* temp = _impl_.colors_.rgba_;
    _impl_.colors_.rgba_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Color::unsafe_arena_set_allocated_rgba(::transport_catalog_serialize::RGBA* rgba) {
  clear_colors();
  if (rgba) {
    set_has_rgba();
    _impl_.colors_.rgba_ = rgba;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalog_serialize.Color.rgba)
}
inline ::transport_catalog_serialize::RGBA* Color::_internal_mutable_rgba() {
  if (!_internal_has_rgba()) {
    clear_colors();
    set_has_rgba();
    _impl_.colors_.rgba_ = CreateMaybeMessage< ::transport_catalog_serialize::RGBA >(GetArenaForAllocation());
  }
  return _impl_.colors_.rgba_;
}
inline ::transport_catalog_serialize::RGBA* Color::mutable_rgba() {
  ::transport_catalog_serialize::RGBA* _msg = _internal_mutable_rgba();
  // @@protoc_insertion_point(field_mutable:transport_catalog_serialize.Color.rgba)
  return _msg;
}

inline bool Color::has_colors() const {
  return colors_case() != COLORS_NOT_SET;
}
inline void Color::clear_has_colors() {
  _impl_._oneof_case_[0] = COLORS_NOT_SET;
}
inline Color::ColorsCase Color::colors_case() const {
  return Color::ColorsCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace transport_catalog_serialize

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_svg_2eproto
