// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport_catalogue.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_transport_5fcatalogue_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_transport_5fcatalogue_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "map_renderer.pb.h"
#include "transport_router.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_transport_5fcatalogue_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_transport_5fcatalogue_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_transport_5fcatalogue_2eproto;
namespace transport_catalog_serialize {
class Bus;
struct BusDefaultTypeInternal;
extern BusDefaultTypeInternal _Bus_default_instance_;
class Coordinates;
struct CoordinatesDefaultTypeInternal;
extern CoordinatesDefaultTypeInternal _Coordinates_default_instance_;
class Distance;
struct DistanceDefaultTypeInternal;
extern DistanceDefaultTypeInternal _Distance_default_instance_;
class Stop;
struct StopDefaultTypeInternal;
extern StopDefaultTypeInternal _Stop_default_instance_;
class TransportCatalogue;
struct TransportCatalogueDefaultTypeInternal;
extern TransportCatalogueDefaultTypeInternal _TransportCatalogue_default_instance_;
class TransportCatalogue_StopsEntry_DoNotUse;
struct TransportCatalogue_StopsEntry_DoNotUseDefaultTypeInternal;
extern TransportCatalogue_StopsEntry_DoNotUseDefaultTypeInternal _TransportCatalogue_StopsEntry_DoNotUse_default_instance_;
}  // namespace transport_catalog_serialize
PROTOBUF_NAMESPACE_OPEN
template<> ::transport_catalog_serialize::Bus* Arena::CreateMaybeMessage<::transport_catalog_serialize::Bus>(Arena*);
template<> ::transport_catalog_serialize::Coordinates* Arena::CreateMaybeMessage<::transport_catalog_serialize::Coordinates>(Arena*);
template<> ::transport_catalog_serialize::Distance* Arena::CreateMaybeMessage<::transport_catalog_serialize::Distance>(Arena*);
template<> ::transport_catalog_serialize::Stop* Arena::CreateMaybeMessage<::transport_catalog_serialize::Stop>(Arena*);
template<> ::transport_catalog_serialize::TransportCatalogue* Arena::CreateMaybeMessage<::transport_catalog_serialize::TransportCatalogue>(Arena*);
template<> ::transport_catalog_serialize::TransportCatalogue_StopsEntry_DoNotUse* Arena::CreateMaybeMessage<::transport_catalog_serialize::TransportCatalogue_StopsEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace transport_catalog_serialize {

// ===================================================================

class Coordinates final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalog_serialize.Coordinates) */ {
 public:
  inline Coordinates() : Coordinates(nullptr) {}
  ~Coordinates() override;
  explicit PROTOBUF_CONSTEXPR Coordinates(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Coordinates(const Coordinates& from);
  Coordinates(Coordinates&& from) noexcept
    : Coordinates() {
    *this = ::std::move(from);
  }

  inline Coordinates& operator=(const Coordinates& from) {
    CopyFrom(from);
    return *this;
  }
  inline Coordinates& operator=(Coordinates&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Coordinates& default_instance() {
    return *internal_default_instance();
  }
  static inline const Coordinates* internal_default_instance() {
    return reinterpret_cast<const Coordinates*>(
               &_Coordinates_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Coordinates& a, Coordinates& b) {
    a.Swap(&b);
  }
  inline void Swap(Coordinates* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Coordinates* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Coordinates* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Coordinates>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Coordinates& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Coordinates& from) {
    Coordinates::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Coordinates* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalog_serialize.Coordinates";
  }
  protected:
  explicit Coordinates(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLatitudeFieldNumber = 1,
    kLongitudeFieldNumber = 2,
  };
  // double latitude = 1;
  void clear_latitude();
  double latitude() const;
  void set_latitude(double value);
  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);
  public:

  // double longitude = 2;
  void clear_longitude();
  double longitude() const;
  void set_longitude(double value);
  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);
  public:

  // @@protoc_insertion_point(class_scope:transport_catalog_serialize.Coordinates)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double latitude_;
    double longitude_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transport_5fcatalogue_2eproto;
};
// -------------------------------------------------------------------

class Stop final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalog_serialize.Stop) */ {
 public:
  inline Stop() : Stop(nullptr) {}
  ~Stop() override;
  explicit PROTOBUF_CONSTEXPR Stop(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Stop(const Stop& from);
  Stop(Stop&& from) noexcept
    : Stop() {
    *this = ::std::move(from);
  }

  inline Stop& operator=(const Stop& from) {
    CopyFrom(from);
    return *this;
  }
  inline Stop& operator=(Stop&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Stop& default_instance() {
    return *internal_default_instance();
  }
  static inline const Stop* internal_default_instance() {
    return reinterpret_cast<const Stop*>(
               &_Stop_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Stop& a, Stop& b) {
    a.Swap(&b);
  }
  inline void Swap(Stop* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Stop* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Stop* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Stop>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Stop& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Stop& from) {
    Stop::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Stop* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalog_serialize.Stop";
  }
  protected:
  explicit Stop(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kCoordinatesFieldNumber = 2,
  };
  // bytes name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .transport_catalog_serialize.Coordinates coordinates = 2;
  bool has_coordinates() const;
  private:
  bool _internal_has_coordinates() const;
  public:
  void clear_coordinates();
  const ::transport_catalog_serialize::Coordinates& coordinates() const;
  PROTOBUF_NODISCARD ::transport_catalog_serialize::Coordinates* release_coordinates();
  ::transport_catalog_serialize::Coordinates* mutable_coordinates();
  void set_allocated_coordinates(::transport_catalog_serialize::Coordinates* coordinates);
  private:
  const ::transport_catalog_serialize::Coordinates& _internal_coordinates() const;
  ::transport_catalog_serialize::Coordinates* _internal_mutable_coordinates();
  public:
  void unsafe_arena_set_allocated_coordinates(
      ::transport_catalog_serialize::Coordinates* coordinates);
  ::transport_catalog_serialize::Coordinates* unsafe_arena_release_coordinates();

  // @@protoc_insertion_point(class_scope:transport_catalog_serialize.Stop)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::transport_catalog_serialize::Coordinates* coordinates_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transport_5fcatalogue_2eproto;
};
// -------------------------------------------------------------------

class Bus final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalog_serialize.Bus) */ {
 public:
  inline Bus() : Bus(nullptr) {}
  ~Bus() override;
  explicit PROTOBUF_CONSTEXPR Bus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Bus(const Bus& from);
  Bus(Bus&& from) noexcept
    : Bus() {
    *this = ::std::move(from);
  }

  inline Bus& operator=(const Bus& from) {
    CopyFrom(from);
    return *this;
  }
  inline Bus& operator=(Bus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Bus& default_instance() {
    return *internal_default_instance();
  }
  static inline const Bus* internal_default_instance() {
    return reinterpret_cast<const Bus*>(
               &_Bus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Bus& a, Bus& b) {
    a.Swap(&b);
  }
  inline void Swap(Bus* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Bus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Bus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Bus>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Bus& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Bus& from) {
    Bus::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Bus* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalog_serialize.Bus";
  }
  protected:
  explicit Bus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStopIdFieldNumber = 2,
    kNameFieldNumber = 1,
    kIsRoundtripFieldNumber = 3,
  };
  // repeated uint64 stop_id = 2;
  int stop_id_size() const;
  private:
  int _internal_stop_id_size() const;
  public:
  void clear_stop_id();
  private:
  uint64_t _internal_stop_id(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      _internal_stop_id() const;
  void _internal_add_stop_id(uint64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      _internal_mutable_stop_id();
  public:
  uint64_t stop_id(int index) const;
  void set_stop_id(int index, uint64_t value);
  void add_stop_id(uint64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      stop_id() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      mutable_stop_id();

  // bytes name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // bool is_roundtrip = 3;
  void clear_is_roundtrip();
  bool is_roundtrip() const;
  void set_is_roundtrip(bool value);
  private:
  bool _internal_is_roundtrip() const;
  void _internal_set_is_roundtrip(bool value);
  public:

  // @@protoc_insertion_point(class_scope:transport_catalog_serialize.Bus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t > stop_id_;
    mutable std::atomic<int> _stop_id_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    bool is_roundtrip_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transport_5fcatalogue_2eproto;
};
// -------------------------------------------------------------------

class Distance final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalog_serialize.Distance) */ {
 public:
  inline Distance() : Distance(nullptr) {}
  ~Distance() override;
  explicit PROTOBUF_CONSTEXPR Distance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Distance(const Distance& from);
  Distance(Distance&& from) noexcept
    : Distance() {
    *this = ::std::move(from);
  }

  inline Distance& operator=(const Distance& from) {
    CopyFrom(from);
    return *this;
  }
  inline Distance& operator=(Distance&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Distance& default_instance() {
    return *internal_default_instance();
  }
  static inline const Distance* internal_default_instance() {
    return reinterpret_cast<const Distance*>(
               &_Distance_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Distance& a, Distance& b) {
    a.Swap(&b);
  }
  inline void Swap(Distance* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Distance* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Distance* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Distance>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Distance& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Distance& from) {
    Distance::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Distance* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalog_serialize.Distance";
  }
  protected:
  explicit Distance(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStopIdFromFieldNumber = 1,
    kStopIdToFieldNumber = 2,
    kDistanceFieldNumber = 3,
  };
  // uint64 stop_id_from = 1;
  void clear_stop_id_from();
  uint64_t stop_id_from() const;
  void set_stop_id_from(uint64_t value);
  private:
  uint64_t _internal_stop_id_from() const;
  void _internal_set_stop_id_from(uint64_t value);
  public:

  // uint64 stop_id_to = 2;
  void clear_stop_id_to();
  uint64_t stop_id_to() const;
  void set_stop_id_to(uint64_t value);
  private:
  uint64_t _internal_stop_id_to() const;
  void _internal_set_stop_id_to(uint64_t value);
  public:

  // double distance = 3;
  void clear_distance();
  double distance() const;
  void set_distance(double value);
  private:
  double _internal_distance() const;
  void _internal_set_distance(double value);
  public:

  // @@protoc_insertion_point(class_scope:transport_catalog_serialize.Distance)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t stop_id_from_;
    uint64_t stop_id_to_;
    double distance_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transport_5fcatalogue_2eproto;
};
// -------------------------------------------------------------------

class TransportCatalogue_StopsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TransportCatalogue_StopsEntry_DoNotUse, 
    uint64_t, ::transport_catalog_serialize::Stop,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TransportCatalogue_StopsEntry_DoNotUse, 
    uint64_t, ::transport_catalog_serialize::Stop,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  TransportCatalogue_StopsEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR TransportCatalogue_StopsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit TransportCatalogue_StopsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const TransportCatalogue_StopsEntry_DoNotUse& other);
  static const TransportCatalogue_StopsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const TransportCatalogue_StopsEntry_DoNotUse*>(&_TransportCatalogue_StopsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_transport_5fcatalogue_2eproto;
};

// -------------------------------------------------------------------

class TransportCatalogue final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transport_catalog_serialize.TransportCatalogue) */ {
 public:
  inline TransportCatalogue() : TransportCatalogue(nullptr) {}
  ~TransportCatalogue() override;
  explicit PROTOBUF_CONSTEXPR TransportCatalogue(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TransportCatalogue(const TransportCatalogue& from);
  TransportCatalogue(TransportCatalogue&& from) noexcept
    : TransportCatalogue() {
    *this = ::std::move(from);
  }

  inline TransportCatalogue& operator=(const TransportCatalogue& from) {
    CopyFrom(from);
    return *this;
  }
  inline TransportCatalogue& operator=(TransportCatalogue&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TransportCatalogue& default_instance() {
    return *internal_default_instance();
  }
  static inline const TransportCatalogue* internal_default_instance() {
    return reinterpret_cast<const TransportCatalogue*>(
               &_TransportCatalogue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(TransportCatalogue& a, TransportCatalogue& b) {
    a.Swap(&b);
  }
  inline void Swap(TransportCatalogue* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TransportCatalogue* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TransportCatalogue* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TransportCatalogue>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TransportCatalogue& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TransportCatalogue& from) {
    TransportCatalogue::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransportCatalogue* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transport_catalog_serialize.TransportCatalogue";
  }
  protected:
  explicit TransportCatalogue(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kStopsFieldNumber = 1,
    kBusFieldNumber = 2,
    kDistanceFieldNumber = 3,
    kMapSettingsFieldNumber = 4,
    kRouterSettingsFieldNumber = 5,
  };
  // map<uint64, .transport_catalog_serialize.Stop> stops = 1;
  int stops_size() const;
  private:
  int _internal_stops_size() const;
  public:
  void clear_stops();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::transport_catalog_serialize::Stop >&
      _internal_stops() const;
  ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::transport_catalog_serialize::Stop >*
      _internal_mutable_stops();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::transport_catalog_serialize::Stop >&
      stops() const;
  ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::transport_catalog_serialize::Stop >*
      mutable_stops();

  // repeated .transport_catalog_serialize.Bus bus = 2;
  int bus_size() const;
  private:
  int _internal_bus_size() const;
  public:
  void clear_bus();
  ::transport_catalog_serialize::Bus* mutable_bus(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalog_serialize::Bus >*
      mutable_bus();
  private:
  const ::transport_catalog_serialize::Bus& _internal_bus(int index) const;
  ::transport_catalog_serialize::Bus* _internal_add_bus();
  public:
  const ::transport_catalog_serialize::Bus& bus(int index) const;
  ::transport_catalog_serialize::Bus* add_bus();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalog_serialize::Bus >&
      bus() const;

  // repeated .transport_catalog_serialize.Distance distance = 3;
  int distance_size() const;
  private:
  int _internal_distance_size() const;
  public:
  void clear_distance();
  ::transport_catalog_serialize::Distance* mutable_distance(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalog_serialize::Distance >*
      mutable_distance();
  private:
  const ::transport_catalog_serialize::Distance& _internal_distance(int index) const;
  ::transport_catalog_serialize::Distance* _internal_add_distance();
  public:
  const ::transport_catalog_serialize::Distance& distance(int index) const;
  ::transport_catalog_serialize::Distance* add_distance();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalog_serialize::Distance >&
      distance() const;

  // .transport_catalog_serialize.MapSettings map_settings = 4;
  bool has_map_settings() const;
  private:
  bool _internal_has_map_settings() const;
  public:
  void clear_map_settings();
  const ::transport_catalog_serialize::MapSettings& map_settings() const;
  PROTOBUF_NODISCARD ::transport_catalog_serialize::MapSettings* release_map_settings();
  ::transport_catalog_serialize::MapSettings* mutable_map_settings();
  void set_allocated_map_settings(::transport_catalog_serialize::MapSettings* map_settings);
  private:
  const ::transport_catalog_serialize::MapSettings& _internal_map_settings() const;
  ::transport_catalog_serialize::MapSettings* _internal_mutable_map_settings();
  public:
  void unsafe_arena_set_allocated_map_settings(
      ::transport_catalog_serialize::MapSettings* map_settings);
  ::transport_catalog_serialize::MapSettings* unsafe_arena_release_map_settings();

  // .transport_catalog_serialize.RouterSettings router_settings = 5;
  bool has_router_settings() const;
  private:
  bool _internal_has_router_settings() const;
  public:
  void clear_router_settings();
  const ::transport_catalog_serialize::RouterSettings& router_settings() const;
  PROTOBUF_NODISCARD ::transport_catalog_serialize::RouterSettings* release_router_settings();
  ::transport_catalog_serialize::RouterSettings* mutable_router_settings();
  void set_allocated_router_settings(::transport_catalog_serialize::RouterSettings* router_settings);
  private:
  const ::transport_catalog_serialize::RouterSettings& _internal_router_settings() const;
  ::transport_catalog_serialize::RouterSettings* _internal_mutable_router_settings();
  public:
  void unsafe_arena_set_allocated_router_settings(
      ::transport_catalog_serialize::RouterSettings* router_settings);
  ::transport_catalog_serialize::RouterSettings* unsafe_arena_release_router_settings();

  // @@protoc_insertion_point(class_scope:transport_catalog_serialize.TransportCatalogue)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        TransportCatalogue_StopsEntry_DoNotUse,
        uint64_t, ::transport_catalog_serialize::Stop,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT64,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> stops_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalog_serialize::Bus > bus_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalog_serialize::Distance > distance_;
    ::transport_catalog_serialize::MapSettings* map_settings_;
    ::transport_catalog_serialize::RouterSettings* router_settings_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transport_5fcatalogue_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Coordinates

// double latitude = 1;
inline void Coordinates::clear_latitude() {
  _impl_.latitude_ = 0;
}
inline double Coordinates::_internal_latitude() const {
  return _impl_.latitude_;
}
inline double Coordinates::latitude() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Coordinates.latitude)
  return _internal_latitude();
}
inline void Coordinates::_internal_set_latitude(double value) {
  
  _impl_.latitude_ = value;
}
inline void Coordinates::set_latitude(double value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Coordinates.latitude)
}

// double longitude = 2;
inline void Coordinates::clear_longitude() {
  _impl_.longitude_ = 0;
}
inline double Coordinates::_internal_longitude() const {
  return _impl_.longitude_;
}
inline double Coordinates::longitude() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Coordinates.longitude)
  return _internal_longitude();
}
inline void Coordinates::_internal_set_longitude(double value) {
  
  _impl_.longitude_ = value;
}
inline void Coordinates::set_longitude(double value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Coordinates.longitude)
}

// -------------------------------------------------------------------

// Stop

// bytes name = 1;
inline void Stop::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Stop::name() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Stop.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Stop::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Stop.name)
}
inline std::string* Stop::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:transport_catalog_serialize.Stop.name)
  return _s;
}
inline const std::string& Stop::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Stop::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Stop::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Stop::release_name() {
  // @@protoc_insertion_point(field_release:transport_catalog_serialize.Stop.name)
  return _impl_.name_.Release();
}
inline void Stop::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:transport_catalog_serialize.Stop.name)
}

// .transport_catalog_serialize.Coordinates coordinates = 2;
inline bool Stop::_internal_has_coordinates() const {
  return this != internal_default_instance() && _impl_.coordinates_ != nullptr;
}
inline bool Stop::has_coordinates() const {
  return _internal_has_coordinates();
}
inline void Stop::clear_coordinates() {
  if (GetArenaForAllocation() == nullptr && _impl_.coordinates_ != nullptr) {
    delete _impl_.coordinates_;
  }
  _impl_.coordinates_ = nullptr;
}
inline const ::transport_catalog_serialize::Coordinates& Stop::_internal_coordinates() const {
  const ::transport_catalog_serialize::Coordinates* p = _impl_.coordinates_;
  return p != nullptr ? *p : reinterpret_cast<const ::transport_catalog_serialize::Coordinates&>(
      ::transport_catalog_serialize::_Coordinates_default_instance_);
}
inline const ::transport_catalog_serialize::Coordinates& Stop::coordinates() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Stop.coordinates)
  return _internal_coordinates();
}
inline void Stop::unsafe_arena_set_allocated_coordinates(
    ::transport_catalog_serialize::Coordinates* coordinates) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.coordinates_);
  }
  _impl_.coordinates_ = coordinates;
  if (coordinates) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalog_serialize.Stop.coordinates)
}
inline ::transport_catalog_serialize::Coordinates* Stop::release_coordinates() {
  
  ::transport_catalog_serialize::Coordinates* temp = _impl_.coordinates_;
  _impl_.coordinates_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::transport_catalog_serialize::Coordinates* Stop::unsafe_arena_release_coordinates() {
  // @@protoc_insertion_point(field_release:transport_catalog_serialize.Stop.coordinates)
  
  ::transport_catalog_serialize::Coordinates* temp = _impl_.coordinates_;
  _impl_.coordinates_ = nullptr;
  return temp;
}
inline ::transport_catalog_serialize::Coordinates* Stop::_internal_mutable_coordinates() {
  
  if (_impl_.coordinates_ == nullptr) {
    auto* p = CreateMaybeMessage<::transport_catalog_serialize::Coordinates>(GetArenaForAllocation());
    _impl_.coordinates_ = p;
  }
  return _impl_.coordinates_;
}
inline ::transport_catalog_serialize::Coordinates* Stop::mutable_coordinates() {
  ::transport_catalog_serialize::Coordinates* _msg = _internal_mutable_coordinates();
  // @@protoc_insertion_point(field_mutable:transport_catalog_serialize.Stop.coordinates)
  return _msg;
}
inline void Stop::set_allocated_coordinates(::transport_catalog_serialize::Coordinates* coordinates) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.coordinates_;
  }
  if (coordinates) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(coordinates);
    if (message_arena != submessage_arena) {
      coordinates = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, coordinates, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.coordinates_ = coordinates;
  // @@protoc_insertion_point(field_set_allocated:transport_catalog_serialize.Stop.coordinates)
}

// -------------------------------------------------------------------

// Bus

// bytes name = 1;
inline void Bus::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Bus::name() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Bus.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Bus::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Bus.name)
}
inline std::string* Bus::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:transport_catalog_serialize.Bus.name)
  return _s;
}
inline const std::string& Bus::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Bus::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Bus::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Bus::release_name() {
  // @@protoc_insertion_point(field_release:transport_catalog_serialize.Bus.name)
  return _impl_.name_.Release();
}
inline void Bus::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:transport_catalog_serialize.Bus.name)
}

// repeated uint64 stop_id = 2;
inline int Bus::_internal_stop_id_size() const {
  return _impl_.stop_id_.size();
}
inline int Bus::stop_id_size() const {
  return _internal_stop_id_size();
}
inline void Bus::clear_stop_id() {
  _impl_.stop_id_.Clear();
}
inline uint64_t Bus::_internal_stop_id(int index) const {
  return _impl_.stop_id_.Get(index);
}
inline uint64_t Bus::stop_id(int index) const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Bus.stop_id)
  return _internal_stop_id(index);
}
inline void Bus::set_stop_id(int index, uint64_t value) {
  _impl_.stop_id_.Set(index, value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Bus.stop_id)
}
inline void Bus::_internal_add_stop_id(uint64_t value) {
  _impl_.stop_id_.Add(value);
}
inline void Bus::add_stop_id(uint64_t value) {
  _internal_add_stop_id(value);
  // @@protoc_insertion_point(field_add:transport_catalog_serialize.Bus.stop_id)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
Bus::_internal_stop_id() const {
  return _impl_.stop_id_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
Bus::stop_id() const {
  // @@protoc_insertion_point(field_list:transport_catalog_serialize.Bus.stop_id)
  return _internal_stop_id();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
Bus::_internal_mutable_stop_id() {
  return &_impl_.stop_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
Bus::mutable_stop_id() {
  // @@protoc_insertion_point(field_mutable_list:transport_catalog_serialize.Bus.stop_id)
  return _internal_mutable_stop_id();
}

// bool is_roundtrip = 3;
inline void Bus::clear_is_roundtrip() {
  _impl_.is_roundtrip_ = false;
}
inline bool Bus::_internal_is_roundtrip() const {
  return _impl_.is_roundtrip_;
}
inline bool Bus::is_roundtrip() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Bus.is_roundtrip)
  return _internal_is_roundtrip();
}
inline void Bus::_internal_set_is_roundtrip(bool value) {
  
  _impl_.is_roundtrip_ = value;
}
inline void Bus::set_is_roundtrip(bool value) {
  _internal_set_is_roundtrip(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Bus.is_roundtrip)
}

// -------------------------------------------------------------------

// Distance

// uint64 stop_id_from = 1;
inline void Distance::clear_stop_id_from() {
  _impl_.stop_id_from_ = uint64_t{0u};
}
inline uint64_t Distance::_internal_stop_id_from() const {
  return _impl_.stop_id_from_;
}
inline uint64_t Distance::stop_id_from() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Distance.stop_id_from)
  return _internal_stop_id_from();
}
inline void Distance::_internal_set_stop_id_from(uint64_t value) {
  
  _impl_.stop_id_from_ = value;
}
inline void Distance::set_stop_id_from(uint64_t value) {
  _internal_set_stop_id_from(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Distance.stop_id_from)
}

// uint64 stop_id_to = 2;
inline void Distance::clear_stop_id_to() {
  _impl_.stop_id_to_ = uint64_t{0u};
}
inline uint64_t Distance::_internal_stop_id_to() const {
  return _impl_.stop_id_to_;
}
inline uint64_t Distance::stop_id_to() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Distance.stop_id_to)
  return _internal_stop_id_to();
}
inline void Distance::_internal_set_stop_id_to(uint64_t value) {
  
  _impl_.stop_id_to_ = value;
}
inline void Distance::set_stop_id_to(uint64_t value) {
  _internal_set_stop_id_to(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Distance.stop_id_to)
}

// double distance = 3;
inline void Distance::clear_distance() {
  _impl_.distance_ = 0;
}
inline double Distance::_internal_distance() const {
  return _impl_.distance_;
}
inline double Distance::distance() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.Distance.distance)
  return _internal_distance();
}
inline void Distance::_internal_set_distance(double value) {
  
  _impl_.distance_ = value;
}
inline void Distance::set_distance(double value) {
  _internal_set_distance(value);
  // @@protoc_insertion_point(field_set:transport_catalog_serialize.Distance.distance)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// TransportCatalogue

// map<uint64, .transport_catalog_serialize.Stop> stops = 1;
inline int TransportCatalogue::_internal_stops_size() const {
  return _impl_.stops_.size();
}
inline int TransportCatalogue::stops_size() const {
  return _internal_stops_size();
}
inline void TransportCatalogue::clear_stops() {
  _impl_.stops_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::transport_catalog_serialize::Stop >&
TransportCatalogue::_internal_stops() const {
  return _impl_.stops_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::transport_catalog_serialize::Stop >&
TransportCatalogue::stops() const {
  // @@protoc_insertion_point(field_map:transport_catalog_serialize.TransportCatalogue.stops)
  return _internal_stops();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::transport_catalog_serialize::Stop >*
TransportCatalogue::_internal_mutable_stops() {
  return _impl_.stops_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< uint64_t, ::transport_catalog_serialize::Stop >*
TransportCatalogue::mutable_stops() {
  // @@protoc_insertion_point(field_mutable_map:transport_catalog_serialize.TransportCatalogue.stops)
  return _internal_mutable_stops();
}

// repeated .transport_catalog_serialize.Bus bus = 2;
inline int TransportCatalogue::_internal_bus_size() const {
  return _impl_.bus_.size();
}
inline int TransportCatalogue::bus_size() const {
  return _internal_bus_size();
}
inline void TransportCatalogue::clear_bus() {
  _impl_.bus_.Clear();
}
inline ::transport_catalog_serialize::Bus* TransportCatalogue::mutable_bus(int index) {
  // @@protoc_insertion_point(field_mutable:transport_catalog_serialize.TransportCatalogue.bus)
  return _impl_.bus_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalog_serialize::Bus >*
TransportCatalogue::mutable_bus() {
  // @@protoc_insertion_point(field_mutable_list:transport_catalog_serialize.TransportCatalogue.bus)
  return &_impl_.bus_;
}
inline const ::transport_catalog_serialize::Bus& TransportCatalogue::_internal_bus(int index) const {
  return _impl_.bus_.Get(index);
}
inline const ::transport_catalog_serialize::Bus& TransportCatalogue::bus(int index) const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.TransportCatalogue.bus)
  return _internal_bus(index);
}
inline ::transport_catalog_serialize::Bus* TransportCatalogue::_internal_add_bus() {
  return _impl_.bus_.Add();
}
inline ::transport_catalog_serialize::Bus* TransportCatalogue::add_bus() {
  ::transport_catalog_serialize::Bus* _add = _internal_add_bus();
  // @@protoc_insertion_point(field_add:transport_catalog_serialize.TransportCatalogue.bus)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalog_serialize::Bus >&
TransportCatalogue::bus() const {
  // @@protoc_insertion_point(field_list:transport_catalog_serialize.TransportCatalogue.bus)
  return _impl_.bus_;
}

// repeated .transport_catalog_serialize.Distance distance = 3;
inline int TransportCatalogue::_internal_distance_size() const {
  return _impl_.distance_.size();
}
inline int TransportCatalogue::distance_size() const {
  return _internal_distance_size();
}
inline void TransportCatalogue::clear_distance() {
  _impl_.distance_.Clear();
}
inline ::transport_catalog_serialize::Distance* TransportCatalogue::mutable_distance(int index) {
  // @@protoc_insertion_point(field_mutable:transport_catalog_serialize.TransportCatalogue.distance)
  return _impl_.distance_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalog_serialize::Distance >*
TransportCatalogue::mutable_distance() {
  // @@protoc_insertion_point(field_mutable_list:transport_catalog_serialize.TransportCatalogue.distance)
  return &_impl_.distance_;
}
inline const ::transport_catalog_serialize::Distance& TransportCatalogue::_internal_distance(int index) const {
  return _impl_.distance_.Get(index);
}
inline const ::transport_catalog_serialize::Distance& TransportCatalogue::distance(int index) const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.TransportCatalogue.distance)
  return _internal_distance(index);
}
inline ::transport_catalog_serialize::Distance* TransportCatalogue::_internal_add_distance() {
  return _impl_.distance_.Add();
}
inline ::transport_catalog_serialize::Distance* TransportCatalogue::add_distance() {
  ::transport_catalog_serialize::Distance* _add = _internal_add_distance();
  // @@protoc_insertion_point(field_add:transport_catalog_serialize.TransportCatalogue.distance)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::transport_catalog_serialize::Distance >&
TransportCatalogue::distance() const {
  // @@protoc_insertion_point(field_list:transport_catalog_serialize.TransportCatalogue.distance)
  return _impl_.distance_;
}

// .transport_catalog_serialize.MapSettings map_settings = 4;
inline bool TransportCatalogue::_internal_has_map_settings() const {
  return this != internal_default_instance() && _impl_.map_settings_ != nullptr;
}
inline bool TransportCatalogue::has_map_settings() const {
  return _internal_has_map_settings();
}
inline const ::transport_catalog_serialize::MapSettings& TransportCatalogue::_internal_map_settings() const {
  const ::transport_catalog_serialize::MapSettings* p = _impl_.map_settings_;
  return p != nullptr ? *p : reinterpret_cast<const ::transport_catalog_serialize::MapSettings&>(
      ::transport_catalog_serialize::_MapSettings_default_instance_);
}
inline const ::transport_catalog_serialize::MapSettings& TransportCatalogue::map_settings() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.TransportCatalogue.map_settings)
  return _internal_map_settings();
}
inline void TransportCatalogue::unsafe_arena_set_allocated_map_settings(
    ::transport_catalog_serialize::MapSettings* map_settings) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.map_settings_);
  }
  _impl_.map_settings_ = map_settings;
  if (map_settings) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalog_serialize.TransportCatalogue.map_settings)
}
inline ::transport_catalog_serialize::MapSettings* TransportCatalogue::release_map_settings() {
  
  ::transport_catalog_serialize::MapSettings* temp = _impl_.map_settings_;
  _impl_.map_settings_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::transport_catalog_serialize::MapSettings* TransportCatalogue::unsafe_arena_release_map_settings() {
  // @@protoc_insertion_point(field_release:transport_catalog_serialize.TransportCatalogue.map_settings)
  
  ::transport_catalog_serialize::MapSettings* temp = _impl_.map_settings_;
  _impl_.map_settings_ = nullptr;
  return temp;
}
inline ::transport_catalog_serialize::MapSettings* TransportCatalogue::_internal_mutable_map_settings() {
  
  if (_impl_.map_settings_ == nullptr) {
    auto* p = CreateMaybeMessage<::transport_catalog_serialize::MapSettings>(GetArenaForAllocation());
    _impl_.map_settings_ = p;
  }
  return _impl_.map_settings_;
}
inline ::transport_catalog_serialize::MapSettings* TransportCatalogue::mutable_map_settings() {
  ::transport_catalog_serialize::MapSettings* _msg = _internal_mutable_map_settings();
  // @@protoc_insertion_point(field_mutable:transport_catalog_serialize.TransportCatalogue.map_settings)
  return _msg;
}
inline void TransportCatalogue::set_allocated_map_settings(::transport_catalog_serialize::MapSettings* map_settings) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.map_settings_);
  }
  if (map_settings) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(map_settings));
    if (message_arena != submessage_arena) {
      map_settings = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, map_settings, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.map_settings_ = map_settings;
  // @@protoc_insertion_point(field_set_allocated:transport_catalog_serialize.TransportCatalogue.map_settings)
}

// .transport_catalog_serialize.RouterSettings router_settings = 5;
inline bool TransportCatalogue::_internal_has_router_settings() const {
  return this != internal_default_instance() && _impl_.router_settings_ != nullptr;
}
inline bool TransportCatalogue::has_router_settings() const {
  return _internal_has_router_settings();
}
inline const ::transport_catalog_serialize::RouterSettings& TransportCatalogue::_internal_router_settings() const {
  const ::transport_catalog_serialize::RouterSettings* p = _impl_.router_settings_;
  return p != nullptr ? *p : reinterpret_cast<const ::transport_catalog_serialize::RouterSettings&>(
      ::transport_catalog_serialize::_RouterSettings_default_instance_);
}
inline const ::transport_catalog_serialize::RouterSettings& TransportCatalogue::router_settings() const {
  // @@protoc_insertion_point(field_get:transport_catalog_serialize.TransportCatalogue.router_settings)
  return _internal_router_settings();
}
inline void TransportCatalogue::unsafe_arena_set_allocated_router_settings(
    ::transport_catalog_serialize::RouterSettings* router_settings) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.router_settings_);
  }
  _impl_.router_settings_ = router_settings;
  if (router_settings) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:transport_catalog_serialize.TransportCatalogue.router_settings)
}
inline ::transport_catalog_serialize::RouterSettings* TransportCatalogue::release_router_settings() {
  
  ::transport_catalog_serialize::RouterSettings* temp = _impl_.router_settings_;
  _impl_.router_settings_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::transport_catalog_serialize::RouterSettings* TransportCatalogue::unsafe_arena_release_router_settings() {
  // @@protoc_insertion_point(field_release:transport_catalog_serialize.TransportCatalogue.router_settings)
  
  ::transport_catalog_serialize::RouterSettings* temp = _impl_.router_settings_;
  _impl_.router_settings_ = nullptr;
  return temp;
}
inline ::transport_catalog_serialize::RouterSettings* TransportCatalogue::_internal_mutable_router_settings() {
  
  if (_impl_.router_settings_ == nullptr) {
    auto* p = CreateMaybeMessage<::transport_catalog_serialize::RouterSettings>(GetArenaForAllocation());
    _impl_.router_settings_ = p;
  }
  return _impl_.router_settings_;
}
inline ::transport_catalog_serialize::RouterSettings* TransportCatalogue::mutable_router_settings() {
  ::transport_catalog_serialize::RouterSettings* _msg = _internal_mutable_router_settings();
  // @@protoc_insertion_point(field_mutable:transport_catalog_serialize.TransportCatalogue.router_settings)
  return _msg;
}
inline void TransportCatalogue::set_allocated_router_settings(::transport_catalog_serialize::RouterSettings* router_settings) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.router_settings_);
  }
  if (router_settings) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(router_settings));
    if (message_arena != submessage_arena) {
      router_settings = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, router_settings, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.router_settings_ = router_settings;
  // @@protoc_insertion_point(field_set_allocated:transport_catalog_serialize.TransportCatalogue.router_settings)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace transport_catalog_serialize

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_transport_5fcatalogue_2eproto
